### ISSUE TITLE
Open file in current window

### ISSUE THREAD

**Issue by vad4msiu** [noklesta/SublimeRailsNav#1]
Sorry for my english.

My layout split at 2 window.
For example:
File user.rb opened into 1 window. I'm trying to open user.rb into second window by command ctrl+cmd+m. It automatically jumps into first window. But if I open by command cmd+t then it open in current windows (second). How to make same behavior?

**Comment by noklesta** [comment]
Creating a layout with two views and moving to the second view (by clicking on it or pressing ctrl+2) and pressing ctrl+cmd+m works for me - it opens the model file in the second view. 

Are you sure you don't already have the file opened in the first view? In that case it will jump to the already opened file (it doesn't seem to be possible to open the same file in multiple views in ST2). Or maybe it has something to do with the ST2 version - which version are you using? (I'm using beta build 2195.)

**Comment by vad4msiu** [comment]
I recorded screencast http://clck.ru/d/Ux0hxRCA1AsSV
First time I use command ctrl+cmd+m. Second cmd+t.
I would like behavior as second time. Is it possible?

**Comment by noklesta** [comment]
Ok, so you did actually have the file opened in the first view. Unfortunately, the API call for opening files (sublime.Window.open_file) does not support opening a second copy of the file in another view - the docs say that "If the file is already opened, it will be brought to the front" (cmd+t, which is built-in, probably uses some internal function instead). I'll look into it if the API starts supporting this in the future.

**Comment by vad4msiu** [comment]
It's sad. Second behaving is more predictably than first. Thanks for the answer.
