### ISSUE TITLE
Lost focus from file list

### ISSUE THREAD

**Issue by salf** [noklesta/SublimeRailsNav#11]
If you use two columns layout and continue typing model's name (or controller for example) the cursor will jump to the first file with loosing focus from file list in dialog box. 

This commit (320522a6803190468b28596bcaed3f0f9befcb25) doesn't have an issue.

**Comment by noklesta** [comment]
Fixed by 69dc0e4fa2cb58fb69207313b2b363e31c53fc81. See discussion in #10.

**Comment by salf** [comment]
Thanks for that
