### ISSUE TITLE
support haml and slim

### ISSUE THREAD

**Issue by batizhevsky** [noklesta/SublimeRailsNav#3]
Good day. 
Thank you for your plugin, its great!

In some projects I use haml or slim template engines, but in views list I see only *.erb files. 
Can you fix this, please?

**Comment by noklesta** [comment]
Thanks for the suggestion! I have created a new version that supports Slim templates (you probably need to reload ST2 to make Package Control install the new version). 

Haml was in fact already supported - is it not working for you?

**Comment by batizhevsky** [comment]
sorry,  I made ​​a mistake. I see, haml supported. Thank you!
