### ISSUE TITLE
Opening in next group

### ISSUE THREAD

**Issue by jeloi** [noklesta/SublimeRailsNav#8]
Hi. First off thanks for the awesome plugin. However, when I open a file using a list_rails_xxxxx command, it always opens the file in the next window group over. Is this default/desired behavior or a bug? Is there some way I can turn this feature off? Because I would like the file to be opened in the current group that I am focused on.
Thanks again.

**Comment by jeloi** [comment]
Haha well after 2 seconds of looking at the code I fixed my "issue" by removing a "+ 1" in the file_selected method. I guess this was default behavior. Owell thanks anyways!

**Comment by noklesta** [comment]
Since this is indeed the desired behaviour, I'm closing this. A pull request for making it configurable would be welcome, though.
